# Generated by Django 3.1 on 2020-09-03 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='post_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
