# Generated by Django 3.1 on 2020-09-03 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200903_0545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogger',
            name='url',
        ),
    ]
